# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: docker.io/barnbarn96/predik-epl:latest
        ports:
        - containerPort: 8080
        env:
        - name: FLASK_ENV
          value: "production"

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80  # Port exposed by the service
    targetPort: 8080  # Flask app's container port
    nodePort: 30007
  type: NodePort  # Change to NodePort if not using a cloud provider
